### ISSUE TITLE
VMWare and VirtualBox are both built by default - VMWare Provisioning Failure

### ISSUE THREAD

**Issue by packet-rat** [stucco/demo#2]
VMWare and VirtualBox boxes are both built by default if you have both available on your host.  Don't know if this is intentional or not?  I can edit the stucco.json file to control it manually.  

I've been looking for the VMWare "box" and  just discovered the VMWare build has been stalled for over an hour awaiting manual specification of the proxy settings, software add-ons, grub loader, etc..   After reboot I can't log on with vagrant/vagrant so I suspect there is something wrong in the VMWare auto-provisioning.

It took a couple of hours for the Collectors,etc. to complete on the VB system.  It would be helpful to set expectations for how long the process should take in the docs

![voila_capture 2015-04-05_07-02-41_am](https://cloud.githubusercontent.com/assets/3220193/6996683/2a8c3a1c-db63-11e4-8d2a-dade74b8723d.jpg)

There were a lot of errors (1,000s of lines) during some of the provisioning phases

![voila_capture 2015-04-05_07-24-19_am](https://cloud.githubusercontent.com/assets/3220193/6996702/e65f606a-db64-11e4-847e-558dec4c95fb.jpg)

```
OR] Failed to execute goal on project streaming-processor: Could not resolve dependencies for project gov.ornl.stucco:streaming-processor:jar:1.0.0: The following artifacts could not be resolved: alignment:alignment_v2:jar:2.0.1, gov.pnnl.stucco:doc-server-client-java:jar:1.0.0: Could not find artifact alignment:alignment_v2:jar:2.0.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]\norg.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project streaming-processor: Could not resolve dependencies for project gov.ornl.stucco:streaming-processor:jar:1.0.0: The following artifacts could not be resolved: alignment:alignment_v2:jar:2.0.1, gov.pnnl.stucco:doc-server-client-java:jar:1.0.0: Could not find artifact alignment:alignment_v2:jar:2.0.1 in central (http://repo.maven.apache.org/maven2)\n\tat org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:220)\n\tat o
```

```
    virtualbox-iso:
    virtualbox-iso: TASK: [jgoodall.golang | unarchive copy=no src=/tmp/golang.tgz dest={{ golang_install_prefix }}
    virtualbox-iso: ] ***
    virtualbox-iso: <stucco> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1428225828.43-176267514569776 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1428225828.43-176267514569776 && echo $HOME/.ansible/tmp/ansible-tmp-1428225828.43-176267514569776']
    virtualbox-iso: <stucco> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=etxnryfvrvlkwonadqggqiobxjqscyxl] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-etxnryfvrvlkwonadqggqiobxjqscyxl; rc=flag; [ -r /usr/local ] || rc=2; [ -f /usr/local ] || rc=1; [ -d /usr/local ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc} "/usr/local && exit 0; (python -c '"'"'"'"'"'"'"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1(); afile = open("'"'"'"'"'"'"'"'"'/usr/local'"'"'"'"'"'"'"'"'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0: hasher.update(buf) buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (python -c '"'"'"'"'"'"'"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha(); afile = open("'"'"'"'"'"'"'"'"'/usr/local'"'"'"'"'"'"'"'"'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0: hasher.update(buf) buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (echo '"'"'"'"'"'"'"'"'0 '"'"'"'"'"'"'"'"'/usr/local)'"'"''
    virtualbox-iso: <stucco> PUT /tmp/tmpDRvfQX TO /home/vagrant/.ansible/tmp/ansible-tmp-1428225828.43-176267514569776/unarchive
    virtualbox-iso: <stucco> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=hnjocsnehyaazrjpnqvgnqqgfrtpfhja] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-hnjocsnehyaazrjpnqvgnqqgfrtpfhja; LANG=C LC_CTYPE=C /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1428225828.43-176267514569776/unarchive; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1428225828.43-176267514569776/ >/dev/null 2>&1'"'"''
    virtualbox-iso: changed: [stucco] => {"changed": true, "check_results": {"cmd": "/bin/tar -C \"/usr/local\" --diff -zf \"/tmp/golang.tgz\"", "err": "/bin/tar: go/.hgignore: Warning: Cannot stat: No such file or directory\n/bin/tar: go/.hgtags: Warning: Cannot stat: No such file or directory\n/bin/tar: go/AUTHORS: Warning: Cannot stat: No such file or directory\n/bin/tar: go/CONTRIBUTORS: Warning: Cannot stat: No such file or directory\n/bin/tar: go/LICENSE: Warning: Cannot stat: No such file or directory\n/bin/tar: go/PATENTS: Warning: Cannot stat: No such file or directory\n/bin/tar: go/README: Warning: Cannot stat: No such file or directory\n/bin/tar: go/VERSION: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api/README: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api/except.txt: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api/go1.1.txt: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api/go1.2.txt: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api/go1.3.txt: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api/go1.4.txt: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api/go1.txt: Warning: Cannot stat: No such file or directory\n/bin/tar: go/api/next.txt: Warning: Cannot stat: No such file or directory\n/bin/tar: go/bin: Warning: Cannot stat: No such file or directory\n/bin/tar: go/bin/go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/bin/godoc: Warning: Cannot stat: No such file or directory\n/bin/tar: go/bin/gofmt: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/4years-gopher.png: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/4years-graph.png: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/4years.article: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/5years: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/5years/conferences.jpg: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/5years/gophers5th.jpg: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/5years.article: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/a-conversation-with-the-go-team.article: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/advanced-go-concurrency-patterns.article: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/appengine-dec2013.article: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/building-stathat-with-go.article: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/building-stathat-with-go_stathat_architecture.png: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/building-stathat-with-go_weather.png: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/c-go-cgo.article: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/concurrency-is-not-parallelism.article: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/bool.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/complex1.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/complex2.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/complex3.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/default1.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/default2.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/default3.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/exercise1.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/content/constants/exercise2.go: Warning: Cannot stat: No such file or directory\n/bin/tar: go/blog/

```
